### ISSUE TITLE
Typo in answer key for COMBINE20 SBOL tutorial

### ISSUE THREAD

**Issue by noahsprent** [SynBioDex/Community-Media#5]
This is the tinyest thing, but in running through the tutorial for SBOL from COMBINE20, I noticed that there is a typo for the role of  i13504. In the code there is an extra zero. It reads:
`i13504.roles.append(SO_NS + '00000804')`

But I believe it should be:
`i13504.roles.append(SO_NS + '0000804')`

**Comment by tcmitchell** [comment]
Thanks for letting us know! This will get fixed via https://github.com/SynBioDex/Community-Media/pull/6
